### ISSUE TITLE
Problem with ispell-buffer

### ISSUE THREAD

**Issue by carrete** [rougier/nano-modeline#13]
When `M-x ispell-buffer` is run, nano-modeline obscures the `*Choices*` buffer:

<img width="517" alt="Screen Shot 2021-10-30 at 08 41 59" src="https://user-images.githubusercontent.com/19260155/139531741-146e16c0-db1d-4ba5-ab0b-386a0f52d1a9.png">

Without nano-modeline, this looks like:

<img width="519" alt="Screen Shot 2021-10-30 at 08 50 18" src="https://user-images.githubusercontent.com/19260155/139531794-c0c74f88-c05d-40c9-b954-19c8d1d40d03.png">

I'd be happy to move the `*Choices*` buffer elsewhere but that doesn't seem possible (per my understanding of the ispell source code which could easily be incorrect). I use popper and tried to make it a pop-up but that doesn't work either.

**Comment by rougier** [comment]
I think this might be related to https://github.com/rougier/nano-emacs/issues/38 but we did not find proper solution but to remove the header line for ispell buffer.
