### ISSUE TITLE
nano-modeline causes odd behavior in Info-mode with emacs-28.0.60

### ISSUE THREAD

**Issue by plattfot** [rougier/nano-modeline#14]
# Description
Notice some strange behavior when using `nano-modeline` and navigating in `Info-mode`. When going back or up from a section `next-line` would jump two lines and `previous-line` would go to the previous line but at the start of that line.

# Expected behavior
After going back or up from a section that `next-line` or `previous-line` would behave as normal and go to the next line or previous line.

# Version
Using `emacs-pgtk-native-comp-28.0.60-212.69977ea` from the [flat channel](https://github.com/flatwhatson/guix-channel.git), commit: 
e015e7093eb9dff16abb5ae909fee61ba77fc677 with [guix](https://guix.gnu.org/)

```elisp
(emacs-version)
"GNU Emacs 28.0.60 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)"
```

# Repro

Clone a fresh copy of this repo and checkout the latest commit as of this writing.
```bash
(cd /tmp && git clone https://github.com/rougier/nano-modeline.git)
(cd /tmp/nano-modeline && git checkout 2de3884)
```

Create a file at `/tmp/init.el` with the content:
```elisp
(require 'nano-modeline "/tmp/nano-modeline/nano-modeline.el")
(nano-modeline-mode 1)
```
Run emacs with just `nano-modeline` enabled
```
emacs -Q -l /tmp/init.el
```
Then `M-x info`, press `m` (`Info-menu`) type `Emacs` and hit enter to go to the Emacs manual. Press `u` (`Info-up`) to go back up and press `C-n` (`next-line`) and it will skip the manual under `Emacs` and go to the next. After that the behavior is normal.

Run emacs without nano-modeline
```
emacs -Q 
```
And do the same steps as above and it will go the manual under `Emacs`.

**Comment by plattfot** [comment]
Found the issue, it's in `nano-modeline-info-breadcrumbs` function. The fix is simply to wrap the body in a `save-mark-and-excursion` (you might get away with just a `save-excursion`), that way the `forward-line` in the body will not affect the cursor outside the function. I would create a PR for this but I haven't sign the [fsf copyright assignment](https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html) yet. It's on my to do list, but will probably take a while.

**Comment by rougier** [comment]
Thanks for the report and the fix! I'm waiting for your PR then.

**Comment by plattfot** [comment]
Sorry for the radio silence. I just sent in the final papers to fsf for the copyright assignment, it took a while due to holidays and legal at work.

When I get confirmation from fsf that they have the copyright assignment I'll open up a PR. If you haven't fixed the bug already?

**Comment by rougier** [comment]
If you make the PR, that would be great!

**Comment by plattfot** [comment]
Created PR #31. Still waiting on hearing back from fsf about the copyright assignment. I've tried contacting them twice but still no word. Not sure how long this process should take. Feel like this is taking a bit longer than normal…

But I figured I can at least create the PR for people to test out.

**Comment by plattfot** [comment]
Just an update on my fsf copyright assignment. I finally heard back and reason for it taking time is the disclaimer, it needs to be reviewed by lawyers. No idea how long that will take. But I'll update this issue when I hear from fsf again.

**Comment by DamienCassou** [comment]
I'm getting weird behavior with isearch as well. The `save-excursion` fixes it, thank you!

**Comment by plattfot** [comment]
Sorry for the radio silence. I just received an email that my copyright assignment is now finally done! They finally had some time to review the disclaimer, which raised some questions and that resulted in my employer redoing the disclaimer, removing all the modifications they did. Then it just took a few days for the process to go through.

Feel free to close this issue.
