### ISSUE TITLE
Support for transient buffers

### ISSUE THREAD

**Issue by librarianmage** [rougier/nano-modeline#15]
Hello!

When using a transient buffer, the modeline shows up. Is there a way to make it not do that?

example (cropped because screen size)
![image](https://user-images.githubusercontent.com/12386291/142704877-38797bca-758a-4068-a3e6-cf03196b6953.png)

**Comment by rougier** [comment]
Is there a mode associated with such transient buffer ? If yes, then we can add a special mode for handling this case.
