### ISSUE TITLE
does `nano-modeline-user-mode` work?

### ISSUE THREAD

**Issue by hans-d** [rougier/nano-modeline#16]
given `(funcall ,nano-modeline-user-mode)) `, I can't get `nano-modeline-user-mode` working. My elisp skills are not top notch, so I might be missing something how to properly set the variable to a custom function.
Perhaps an example would help?

**Comment by rougier** [comment]
I think it might be broken actually and it might need to be splitted in two functions. One saying whether to use user-mode or not and the second to return the modeline format when it is used. Do you want to try to fix it and make a Pull Request?
