### ISSUE TITLE
Version 0.3 graphical glitches

### ISSUE THREAD

**Issue by elnawe** [rougier/nano-modeline#20]
Hi, 

I installed `nano-modeline` on version 0.2 and it was working great. Loved the minimal design. Today I changed my package system to straight.el and it pulled 0.3. I noticed some graphical issues and couldn't figure out what it was until I checked versions. I will research more but I thought it was a good idea to open the ticket in case someone updates and see the same issues.

Theme: night-owl-theme
Package system: straight.el (was able to pull 0.2 and it work well again)
Emacs 27.2

Screenshots:

## Version 0.3:
![image](https://user-images.githubusercontent.com/5782706/147373840-78c4a5ec-2488-4be0-94df-5367b9cccefa.png)

**Comment by hans-d** [comment]
I've noticed some "major" changes as well that impacted my customisation as well.

"noticed some graphical issues" What do you mean? And what kind of customisations have you applied?

**Comment by hans-d** [comment]
Looks like this might be fixed with #23

**Comment by elnawe** [comment]
Thank you for the fix. I will try it out. The spacer issue is one I found, the other ones were:
- modeline still showing (sometimes). You opened an issue for that, thanks!
- the inactive nano-modeline also looks broken, like the active one (similar issue to this one)

I haven't applied any customization to it.

**Comment by hans-d** [comment]
Hi, i've provided a workaround for the modeline still showing
The inactive nano-modeline most likely is also fixed by #23

**Comment by elnawe** [comment]
I downloaded #23 but I'm still having the same issues on active and inactive bars, here's the screenshot:

![image](https://user-images.githubusercontent.com/5782706/147525246-5662c4db-8725-4ac6-918d-70162aed5629.png)

Updated the original post to mention I'm using Emacs 27.2

**Comment by hans-d** [comment]
Hi, thanks for the screenshot. I've pushed a small fix.

**Comment by elnawe** [comment]
Just left a comment on #23. The fix works. Thanks!

**Comment by rougier** [comment]
I now understand #23. I will fix it because I think it can be made simpler than the provided patch by @hans-d;

**Comment by hans-d** [comment]
@rougier any update on "I will fix it because I think it can be made simpler than the provided patch"

**Comment by rougier** [comment]
@hans-d No, thanks for the reminder. I think the solution is to define the background of the header-line face with the same background as the active nano modeline face. Problem is that we cannot have different active/inactive background. The other option would be to define a nano-modeline-active and nano-modeline-inactive for spaces between elements (and user is responsible to make them compatible with other elements). What do yout think? Or is you patch simpler?

**Comment by hans-d** [comment]
Well, the patch is already providing an active/inactive face for the spaces ....

**Comment by rougier** [comment]
You're right, sorry. Your patch is correct. It'll need a rebase though.
