### ISSUE TITLE
Suggestion: less hardcoding, more customisation functionality

### ISSUE THREAD

**Issue by hans-d** [rougier/nano-modeline#22]
With v0.3 the number of hardcoded items has increased significantly (eg names of the modes). It would be friendlier if these sections are more customisable, either via variables or - preferred - functions.

With the added overhead, I might make sense to split the mode specific bits into separate files.

**Comment by rougier** [comment]
Fixed with the new [simpler](https://github.com/rougier/nano-modeline/tree/simpler) branch
