### ISSUE TITLE
Bottom position  not shown

### ISSUE THREAD

**Issue by Airwan** [rougier/nano-modeline#28]
Hello,

 I tried your very nice modeline but the bottom position is not shown while top default works fine. I set the ` nano-modeline-position` to `'bottom` with an empty init file however the bottom mode-line is empty (full grey).

Thanks for your help.

**Comment by artelse** [comment]
See issue #24 below.

**Comment by Airwan** [comment]
I think it is not the same problem because I am trying to use the modeline at bottom (not top). And nothing appears neither at top nor at bottom.

**Comment by rougier** [comment]
I just pushed a commit to remove the hook.
