### ISSUE TITLE
Dependency on Magnars/s

### ISSUE THREAD

**Issue by romatthe** [rougier/nano-modeline#3]
Hi,

I was trying to give your (quite beautiful!) package a spin but couldn't get it to work with the following configuration

```elisp
(use-package nano-theme
  :straight (nano-theme :type git
                        :host github
                        :repo "rougier/nano-theme")
  :demand t
  :config
  (nano-dark))

(use-package nano-modeline
  :straight (nano-modeline :type git
                           :host github
                           :repo "rougier/nano-modeline")
  :demand t
  :config
  (nano-modeline))
```

I would constantly get the error

```
Error (use-package): nano-modeline/:catch: Cannot open load file: No such file or directory, s Disable showing Disable logging

File is missing: Cannot open load file, No such file or directory, s
```

It took me a while to realize this, but it was complaining about missing [Magnars' string manipulation package](https://github.com/magnars/s.el), and indeed you swapped out `subr-x` for `s` in 3bfc046.

Now this is easily fixed by requiring the `s` package, but:

- It would be nice if this would be included in the installation instructions
- But it would probably be better to remove the dependency on Magnars' package entirely, as the only functions that is used is `s-truncate` I think, and it's only used twice. (It's possible I'm missing a few instances here, I skimmed through it rather quickly)

What do you think is the best approach?

**Comment by rougier** [comment]
Thanks for the analysis and I think it would be better if we can get rid of the dependency. I think I used in the first place because I could not find the equivalent in elisp (I'm still learning). Do you know if this exists? Else we coudl write our own.
Could you make a PR?

**Comment by rougier** [comment]
Dependency has been removed.
