### ISSUE TITLE
Outdated screenshots

### ISSUE THREAD

**Issue by DamienCassou** [rougier/nano-modeline#32]
The screenshots in the README show mode-specific prefixes but it seems commit d13a11286a88f0d6baac4eda56ecf9eb3019fa0d removed them (without detailing why).

**Comment by rougier** [comment]
Thanks, I've just updated the screenshots. I reverted back to the original vesion (RO/RW/**) because it's more "neutral". But you now have the option to prefix a mode the way you want if you rewrote the specific mode.

**Comment by DamienCassou** [comment]
Thanks to *you*. Your work is fantastic!
