### ISSUE TITLE
Unable to check out repository on Windows

### ISSUE THREAD

**Issue by wagk** [rougier/nano-modeline#35]
Commit eed2de9392e59e07b46537d529453df62b967ec1 added two files `images/nano-modeline-**-focused.png` and `images/nano-modeline-**-unfocused.png`, which contains `*`, a character Windows does not permit in file names.

Attempting to check out the commit on Windows results in the following:
```
128 git.exe … "reset" "--hard" "origin/master" "--"
error: invalid path 'images/nano-modeline-**-focused.png'
fatal: Could not reset index file to revision 'origin/master'.
```

Is it possible to rename these files to some other name?

**Comment by rougier** [comment]
Oh sorry for that. I'll rename them.

**Comment by rougier** [comment]
Done.
