### ISSUE TITLE
Part of transient buffers are hidden

### ISSUE THREAD

**Issue by DamienCassou** [rougier/nano-modeline#37]
When using Magit, I don't see the commands on the last line:

![2022-04-22-200628](https://user-images.githubusercontent.com/217543/164770556-6941e59c-19ca-405f-baa4-f2ef71fb6625.png)

**Comment by rougier** [comment]
What should be displayed exactly? Is it a specific magit mode (for which we could write a specific modeline)?

**Comment by DamienCassou** [comment]
> What should be displayed exactly?

as you can see in the screenshot above, the last line is partially hidden. We should clearly see "k Remove   P Prune stale refspecs"

> Is it a specific magit mode (for which we could write a specific modeline)?

magit is not to blame here. The problem is with the transient library that is used by magit to create popups. To reproduce:

```lisp
(defun my/remove ()
  (interactive)
  (message "my/remove"))

(transient-define-prefix my/foo ()
  "documentation"
  ["Group 1"
   ("k" "remove" my/remove)])
```

and then `M-x my/foo`:

![2022-04-23-100544](https://user-images.githubusercontent.com/217543/164886096-8473d80d-e51e-43da-8e08-5ae555495375.png)

Again, the last line is invisible. With `emacs -Q`, it looks like this instead:

![2022-04-23-101046](https://user-images.githubusercontent.com/217543/164886308-f4038d55-547f-4859-af52-4ed31794023a.png)

I think I will discuss the issue in the transient project because `transient--show` hides the mode-line and the tab-line but not the header-line. Hiding it as well fixes my issue.

**Comment by DamienCassou** [comment]
Here is the transient issue I opened: https://github.com/magit/transient/pull/198.

**Comment by DamienCassou** [comment]
My PR got merged so we can close this issue.
