### ISSUE TITLE
void-function nano-modeline-text-mode 

### ISSUE THREAD

**Issue by artelse** [rougier/nano-modeline#51]
With `emacs -Q` I simply install the package `M-: (package-install 'nano-modeline)`.
I add a hook `(add-hook 'text-mode-hook  #'nano-modeline-text-mode)`.
Enable `text-mode` and get following error: 
`(void-function nano-modeline-text-mode)`
Any idea?

**Comment by rougier** [comment]
Can you try to type `C-h f nano-modeline` and the hit tab to see completion?

**Comment by artelse** [comment]
Latest update fixes the problems. Thanks :)
