### ISSUE TITLE
Cannot get the simpler nano-modeline to work

### ISSUE THREAD

**Issue by yakhni** [rougier/nano-modeline#55]
Hi,
I am trying to do the following:
```
(use-package! nano-modeline
  :config
  (nano-modeline-text-mode t))

```

However, I end up with the following backtrace:
```
Debugger entered--Lisp error: (wrong-type-argument listp nano-modeline--empty-face)
  face-remap-set-base(header-line nano-modeline--empty-face)
  nano-modeline-header(((nano-modeline-buffer-status) " " (nano-modeline-buffer-name) " " (nano-modeline-git-info)) ((nano-modeline-cursor-position) (nano-modeline-window-dedicated)) t)
  funcall(nano-modeline-header ((nano-modeline-buffer-status) " " (nano-modeline-buffer-name) " " (nano-modeline-git-info)) ((nano-modeline-cursor-position) (nano-modeline-window-dedicated)) t)
  nano-modeline-text-mode(t)
```

I'm using emacs 28.2, doom emacs.
I've been using nano-modeline and nano-theme for quite a bit, but I cannot get nano-modeline to run with the new API.
Please advise.

**Comment by coldfish** [comment]
Still getting the same error like @yakhni 

`(wrong-type-argument listp nano-modeline--empty-face)`

**Comment by rougier** [comment]
Might be linked with a fix I pushed a few minutes ago on ELPA. Coudl you try with the github version (I think ELPA still not updated) ?

**Comment by coldfish** [comment]
I'm using the github version directly and see the last commit in my repo list:

```
Author: Nicolas P. Rougier
Date:   Mon Jun 19 16:12:53 2023 +0200

    Minor bugfix for ELPA
```

**Comment by rougier** [comment]
What is your version of emacs?

**Comment by coldfish** [comment]
> What is your version of emacs?

28.2

**Comment by rougier** [comment]
Oh, is it the same issue #59 ?

**Comment by yakhni** [comment]
I am closing this issue since upgrading to emacs version 29.1 resolves this issue.
