### ISSUE TITLE
Support for lsp mode?

### ISSUE THREAD

**Issue by librarianmage** [rougier/nano-modeline#6]
Hi! Sorry for the bother but do you have any suggestions on configuring the modeline to work with lsp-mode? There are two main issues I see:

* the breadcrumbs push the modeline over
* the modeline doesn't have any integration with the things lsp wants to do

is there anything I can do to try to fix this on my end?

**Comment by rougier** [comment]
I'm not sure I understand. Can you show a screenshot of the problem?

**Comment by librarianmage** [comment]
Sure! Sorry for not being clearer :sweat_smile:

lsp-mode adds "breadcrumbs" at the top of the page that push the modeline slightly out of the window:
![image](https://user-images.githubusercontent.com/12386291/135857139-c28dd7ae-2e33-4d01-86c5-1b0b25600b69.png)

Additionally, there are little buttons and things that the mode normally adds to the modeline for interaction with the lsp server. Do you have any recommendations on how to try to add those things back in? If not it doesn't look to be too big of an impediment from lsp-mode's intended workflow, but I am not super familiar with the package yet

**Comment by rougier** [comment]
Do you know if there's a way to disable such breadcrumbs ? Or a hook to modify them ?

**Comment by librarianmage** [comment]
The variable is `lsp-headerline-breadcrumb-mode`

**Comment by rougier** [comment]
Thanks. Maybe worth to have a hook before lsp to disable them. If you look into the code, you'll find that some modes have hook before activation. For the buttons, you can actually define a specific lsp mode that will include those buttons. I can try to help you on that.
