### ISSUE TITLE
Modeline does not utilize global-mode-string

### ISSUE THREAD

**Issue by ReilySiegel** [rougier/nano-modeline#7]
Currently, the modeline does not include global-mode-string. Is this intentional? This causes issues with minor modes that utilize the global-mode-string, such as display-time-mode and display-battery-mode. These modes specifically are useful for those running EXWM.

**Comment by ReilySiegel** [comment]
I would actually recommend appending it to the secondary part. Here is a screenshot of my current modeline (using doom-modeline). The time and battery level are provided by the `global-
![2021-10-08-152754_1476x59_scrot](https://user-images.githubusercontent.com/19987934/136615115-12259ce3-2607-4ea5-8d42-f3e931cec531.png)
mode-string`.

**Comment by rougier** [comment]
Maybe I could add an option on whether or not to include the global mode string in the secondary part. What do you think?

**Comment by ReilySiegel** [comment]
Sorry for the late reply. I think this would be a gread solution to the problem, but depending on how many modes use the global-mode-string, this could get quite crowded. I think a sensible option is to have an option (perhaps called something like `nano-modeline-secondary-part-ext` which when set to `nil` uses the default secondary part, when set to  `t` uses `global-mode-string`, and can also be set to any string in the format of `global-mode-string`, allowing users to exclude specific parts if they so choose. However, doing this greatly increases the complexity of the package, which is counter to the design goals.

**Comment by rougier** [comment]
My turn to be sorry for late reply. having somehing like `nano-modeline-use-global-mode-string` does not seems over complex to me. Would you like to male a PR ?

**Comment by ReilySiegel** [comment]
"Nicolas P. Rougier" ***@***.***> writes:

> My turn to be sorry for late reply.

No worries!

> having somehing like `nano-modeline-use-global-mode-string` does not
> seems over complex to me. Would you like to male a PR ?

I can certainly make a PR, however I don't currently have a lot of free
time, so I can't guarantee how quickly that will come in. I'll put it on
my to-do list, and hopefully no one beats me to it!

**Comment by rougier** [comment]
No problem, if we both continue to answer each other very late, we should converge in January 2022 :)

**Comment by SalTor** [comment]
After looking at the codebase it seems to me this was an abandoned effort. I have seen that a next big version of nano-modeline is in the works, would this change happen to be included in that batch of work?

**Comment by rougier** [comment]
The big change has been merged but I forgot about this issue... Would you like to try to make a PR? Note that we need to decide if each mode decides to use global mode string or not or if this is a global option.
