### ISSUE TITLE
Invisible dedicated-window marker on Windows11

### ISSUE THREAD

**Issue by TomoeMami** [rougier/nano-modeline#71]
What's the symbol of this marker? I can't see it in both browser and Emacs GUI.

[  (propertize (if (window-dedicated-p) (or symbol " ") "")
              'face (nano-modeline-face 'secondary)))](https://github.com/rougier/nano-modeline/blob/631387df3f6835a975faa1f0c8b44da1fe4b57a9/nano-modeline.el#L551C1-L552C54)

I have to re-defun it in my config.el, cause it takes several seconds to load my `popper.el`.

In browser:

![image](https://github.com/rougier/nano-modeline/assets/16950305/c2238f47-9493-4db6-881d-00cb334cb25c)

In Emacs:

![image](https://github.com/rougier/nano-modeline/assets/16950305/0ce314be-27be-4c2a-8da6-bf514dd10124)

![image](https://github.com/rougier/nano-modeline/assets/16950305/119b1a3f-bcfb-4593-9a2c-42e72a62776b)

**Comment by etern** [comment]
install [Symbols Nerd Font](https://www.nerdfonts.com/font-downloads), and use it for this charater: 
`(set-fontset-font t '(#xeba0 . #xeba0) "Symbols Nerd Font Mono")`

**Comment by TomoeMami** [comment]
> Maybe the dedicated marker needs to be customizable and we could check if it is available (if not, fallback to a text marker like "D"). But I don't remember the function to test if a glyph is available.

Maybe we can search `Symbols Nerd Font` as an alternative approach.

`(member "Symbols Nerd Font" (font-family-list))`

**Comment by rougier** [comment]
In my case, I've Installed "Roboto Mono Nerd" so I'm not sure your code would work. And I suspect most user would want their own symbol such that a custom character might b the easy way. What do you think ?

**Comment by TomoeMami** [comment]
Customization is the soul of Emacs. 

In fact, I redefined the function `nano-modeline-window-dedicated`, replacing the `PIN` symbol with a more universal but less precising symbol `▼`.

```
(defun nano-modeline-window-dedicated (&optional symbol)
  "Pin symbol when window is dedicated"
  
  (propertize (if (window-dedicated-p) (or symbol "▼ ") "")
              'face (nano-modeline-face 'secondary)))
```

![image](https://github.com/rougier/nano-modeline/assets/16950305/6d6c5a8f-079f-4c3b-8e42-f5d67e80c6a2)

**Comment by rougier** [comment]
Done.
