### ISSUE TITLE
nano-modeline-mu4e-message-mode blocking opening mu4e message

### ISSUE THREAD

**Issue by rytswd** [rougier/nano-modeline#75]
It seems message cannot be opened up correctly when missing `:name` in the TO or FROM field.

```
error in process filter: nano-modeline-mu4e-message-to: Wrong type argument: char-or-string-p, nil
error in process filter: Wrong type argument: char-or-string-p, nil
```

I tried to add some safety check for `capitalize` and `downcase` function, namely for:
- `to-names` in `nano-modeline-mu4e-message-to`
- `from-name` in `nano-modeline-mu4e-message-from`

And with that, I could see the modeline correctly handled, and opening up the message. It may also be worth making it safe for when `(mu4e-personal-addresses)` returns nil.

**Comment by rougier** [comment]
Thanks for the report. I've just pushed a commit that might solve the problem.

**Comment by rytswd** [comment]
Thank you for the quick fix @rougier, I could confirm it's working correctly for me now!
