### ISSUE TITLE
Inconsistencies with Magit buffers

### ISSUE THREAD

**Issue by protesilaos** [rougier/nano-modeline#8]
Bonjour Nicolas!

I noticed that the mode line has two types of problems with Magit buffers:

1. Diff and commit log buffers do not have a mode line over them.
2. The `M-x magit-status` mode line renders all its contents in a bold weight.

Samples:

## Magit windows

Top left is the `magit-status`, which has a mode line.  Below it is a diff, which has no mode line.  To the right is a log, again with no mode line.

![2021-10-08_09:17:31_1916x1058](https://user-images.githubusercontent.com/12828033/136507585-6639d50e-db8d-4440-8e22-5326eb5653f9.png)

## Magit status is in bold

Notice how the Dired mode line uses the desired font weights.

![2021-10-08_09:14:06_1920x1080](https://user-images.githubusercontent.com/12828033/136507724-db1098e8-87ac-48ef-a572-ec7bbaa0b8f8.png)

![2021-10-08_09:14:14_1920x1080](https://user-images.githubusercontent.com/12828033/136507726-2213cc9f-a5bb-46f9-8018-6df58eb2e5bd.png)

EDIT: This problem does not occur when `(setq nano-modeline-position 'bottom)`.

**Comment by rougier** [comment]
Temporary fix is: `(advice-add 'magit-set-header-line-format :override #'ignore)`

**Comment by sidd897** [comment]
I think with the latest commit, we can now have a permanent fix. We can now advice `:around` the function `magit-set-header-line-format` something like this.

```
(defun nano-modeline-magit-mode (orig-fun input)
    "Nano modeline for magit mode"

    (funcall nano-modeline-position
             `((nano-modeline-buffer-status) " "
               (nano-modeline-buffer-name) " "
               ,(concat "(" input ")"))
             '((nano-modeline-cursor-position)
               (nano-modeline-window-dedicated))))

  (advice-add 'magit-set-header-line-format :around #'nano-modeline-magit-mode)
```
From my quick testing, we can now get the magit's headerline status strings displayed in a style which is consistent with nano-modeline.

**Comment by rougier** [comment]
Oh great, can you make a PR?
